name: AutoReport
version: '${project.version}'
main: hazehenry.autoreport.AutoReport
loadbefore:
  - UltimateAutoRestart
api-version: '1.18'
commands:
  autoreport:
    aliases:
      - ar
      - autorep
      - arp
  chatlog:
    aliases:
      - cl
  suggestword:
    aliases:
      - sw
      - suggest
  arp:
    aliases:
      - autoreportpanel
      - arpanel