name: AutoReport
version: '${project.version}'
main: hazehenry.autoreport.AutoReport
api-version: '1.8'
commands:
  autoreport:
    aliases:
      - ar
      - autorep
      - arp
  chatlog:
    aliases:
      - cl