wordlist:
  - anyád
  - anyad
  - anyd
  - anyud
  - f@sz
  - fasz
  - f.sz
  - fsz
  - faszfej
  - fszfej
  - f4sz
  - f4szfej
  - f4szfj
  - k@r
  - kur
  - k.rva
  - krva
  - kurv
  - b@sz
  - basz
  - b.szd
  - geci
  - g.ci
  - gci
  - puni
  - punci
  - p.nc
  - pina
  - p1na
  - szar
  - szr
  - sz@r
  - fos
  - f0s
  - f0sz
  - nigger
  - niga
  - nigga
  - niggaz
  - niggas
  - niggaz
  - nigger
  - niggers
  - n1gger
  - n1ggers
  - n1gg3r
  - n1gg3rs
  - fuck
  - fuk
  - fck
  - fuk

suggestedwords:
