name: AutoReport
version: '1.0'
main: hazehenry.autoreport.AutoReport
api-version: '1.18'
commands:
  autoreport:
    aliases:
      - ar
      - autorep
      - arp
  chatlog:
    aliases:
      - cl
  suggestword:
    aliases:
      - sw
      - suggest
  arp:
    aliases:
      - autoreportpanel
      - arpanel